[package]
name = "nightcycle/package"
description = "A package!"
version = "0.1.0"
authors = [ "CJ Oyer <coyer@nightcycle.us>",]
realm = "shared"
registry = "https://github.com/upliftgames/wally-index"
exclude = [ "Packages", ".vscode",]

[dependencies]
Maid = "nightcycle/maid@1.1.4"
ColdFusion = "nightcycle/cold-fusion@9.0.7"
Signal = "nightcycle/signal@1.0.2"
FormatUtil = "nightcycle/format-util@1.0.0"
TableUtil = "nightcycle/table-util@1.1.0"